/**
 * Scaffolded AGENTS.md content — written to the ROOT of the generated project.
 *
 * Makes the scaffolded project AI-ready (#203): an agent working inside the
 * generated project gets the conventions without reverse-engineering them
 * from the code (the mechanism that produced #195: LLMs trained on Skeleton v4
 * "know" variant-* exists).
 *
 * Recorded decision (#347): AGENTS.md is the SOLE agent convention of a
 * SvelteForge project. No tool-specific instruction file (Claude, Gemini,
 * Copilot, Cursor, …) is scaffolded, and no sync or drift machinery exists —
 * one file to read, one file to edit. Whether a given tool loads AGENTS.md
 * automatically is that tool's own feature, not something SVForge claims.
 *
 * NOTE: this is a TS constant written via sv.file(), NOT a template file —
 * the prebuild only ships templates/<name>/src/** (gotcha documented in the repo
 * AGENTS.md). A root template file would be silently undelivered.
 */

import { SKELETON_PRIMITIVES, SKELETON_VERSIONS as SKELETON_INVENTORY } from './skeleton-inventory';

const SHARED = (primitives: string, versions: { css: string; svelte: string }, pm: string) => `# AGENTS.md — generated by SvelteForge

Guide for AI agents working in this project.

## Positioning

This project was scaffolded with **SvelteForge** — a fast-start boilerplate,
NOT a component library and NOT a shadcn clone.

- The base UI kit is already in \`src/lib/components/svforge/\`: Button, Input,
  Textarea, Select, Checkbox, Toggle, Card, Badge, Alert, Table + infra
  (ThemeToggle, Seo, Sitemap, Logo). **Do not rewrite them.**
- For richer components use the official components from
  \`@skeletonlabs/skeleton-svelte\` directly. The full installed inventory
  (${primitives}) is protected by \`svforge check\`.
- Do not invent a new design system — build on what's here.

## Skeleton v5 classes — search the LOCAL docs first (LLM knowledge is stale)

This project ships with Skeleton ${versions.css} / Skeleton Svelte ${versions.svelte}
PLUS vendored, version-matched references under \`docs/\`:

- \`docs/llms-skeleton.txt\` — the full Skeleton reference (theme, tokens, utilities, components)
- \`docs/llms-svelte.txt\` — the Svelte 5 / SvelteKit reference

**Before changing Skeleton UI, theme tokens, presets, radius, typography or global CSS:**

1. search docs/llms-skeleton.txt (and \`docs/llms-svelte.txt\` for framework behavior)
2. trust the vendored docs over training memory
3. inspect the primitive/utility there BEFORE adding styling around it

The utility families below are examples — they are NOT exhaustive (Skeleton also
ships typography utilities such as \`h1\`…\`h6\`, \`anchor\`, \`pre\`, \`kbd\`, and the
inventory evolves between releases). Search docs/llms-skeleton.txt before recreating
behavior with Tailwind or custom CSS.

- \`preset-filled-*\` / \`preset-tonal-*\` / \`preset-outlined-*\` (+ color suffixes like \`-primary-500\`, \`-surface-400-600\`)
- component classes: \`btn\`, \`btn-icon\`, \`badge\`, \`chip\`, \`card\`, \`input\`, \`select\`, \`textarea\`, \`checkbox\`, \`table\`, \`label\`
- typography: \`h1\`…\`h6\`, \`anchor\`, \`pre\`, \`kbd\` — driven by the theme's \`--typo-*\` / \`--font-mono\` tokens
- radius: Tailwind scale (\`rounded-lg\`, …) + the theme radii \`rounded-base\` / \`rounded-container\` (from \`--radius-*\`); \`corner-shape-*\` for shapes — NOT invented radii like \`rounded-card\`
- sizes: \`btn-xs…btn-9xl\`, \`btn-icon-*\` — NOT \`btn-md\`; badges have NO size utilities (they scale via their \`--badge-size\` token)

**BLACKLIST — these do NOT exist in v5 (nor v4):**

- \`variant-*\` — this is the OLD Skeleton v2 naming (renamed \`preset-*\` in v3)
- \`preset-ghost\` — use \`preset-outlined-*\` or \`preset-tonal-*\`
- \`alert alert-*\` — Bootstrap classes; use the \`Alert\` component (\`variant="error"\` etc.) or the dashboard \`Feedback\` component
- \`btn-md\`, \`badge-sm\`, \`preset-tonal-info\`, \`input-error\` — invented utilities; \`svforge check\` rejects them

\`svforge check\` validates every class against the actually installed Skeleton inventory: inventing a
utility or stacking two incompatible primitives fails before merge.

## Tailwind/Skeleton class lint (#482)

ESLint validates class names against this project's actual Tailwind v4 + Skeleton CSS entrypoint.
Unknown or custom class names are errors by default; do not invent classes or add custom utilities
just to work around a diagnostic. Keep static class candidates literal in markup and in helpers such
as \`cn()\`, \`clsx()\`, and \`twMerge()\` so lint can inspect them.

This is the generated project's default convention, not a lock on human choices. If custom styling is
intentionally required, a human can add a targeted ESLint disable or change/remove the rule in
\`eslint.config.js\`.

## Advisory vs enforced

This file is **advisory**: it tells agents what to prefer. The mechanical
enforcement is \`npx svforge check\` — design-system violations (second UI kit,
duplicated primitives, invented utilities) fail THERE, not here. This file is
the sole agent convention of the project: keep it accurate when the
conventions change.

## Component conventions (\`src/lib/components/svforge/\`)

Canonical structure (#242) — the filesystem IS the registry:

- \`primitives/\` — small generic bricks: Button, Input, Select, Textarea, Checkbox, Toggle, Badge
- \`ui/\` — composed reusable components: Card, Alert, Table, ThemeToggle, Seo, Logo, Sitemap
- \`layout/\` — page structure: Navbar, Footer

**Before creating a UI component, ALWAYS:**
1. search \`src/lib/components/svforge/primitives/\`
2. search \`src/lib/components/svforge/ui/\`
3. search \`src/lib/components/svforge/layout/\`
4. check if Skeleton already provides it: \`import { X } from '@skeletonlabs/skeleton-svelte'\`
5. create only when no reusable option exists

A domain-specific component does NOT belong in the generic design system —
keep it in its feature area (e.g. \`src/lib/features/...\` or the route folder).

## Composition grammar

- The **shell owns navigation and global context**; page content states its purpose without unnecessarily repeating the shell title.
- A **section** groups related content. A Card is a functional unit, not a default wrapper: use it for a stat, focused form, or bounded detail. Keep lists and tables direct when that better serves scanning.
- Let width follow the content: compact forms, readable prose, wide data views, and field workflows have different needs. No \`max-w-*\` value is a universal rule.
- Give an area **one dominant action**. Use secondary/tonal or outlined actions for supporting work; \`primary\`, \`secondary\`, \`surface\`, and semantic colors describe roles, not a mandatory brand.
- On small screens preserve hierarchy, reading order, readable targets, and no overflow — do not preserve arbitrary desktop dimensions.
- Do not add \`Page*\`/\`Section*\` components just to freeze dimensions; abstract only a genuinely repeated product convention.

Use the existing screens as concrete references, not a gallery to copy: \`/demo-ui\` shows the available building blocks, \`/admin\` is a dashboard with one primary route action, \`/admin/users\` keeps a CRUD list/table direct, and \`/admin/settings\` uses focused form units.

## Design-system contract (#240, #313)

**Reuse first**: prefer reuse over invention. A visually less custom interface
that fully follows the design system is preferred over a bespoke interface
that introduces new patterns. Coherence > originality on first pass.

SvelteForge deliberately scaffolds a very small CSS architecture:

- \`src/routes/layout.css\` is the **single global CSS entrypoint**. Keep it as wiring only: Tailwind, Skeleton, Skeleton Svelte, fonts, plugins, the dark variant, and the import of the SvelteForge theme.
- \`src/lib/styles/svelteforge-theme.css\` is the **complete Skeleton v5 theme** and the visual source of truth for palettes, surfaces, brand, root backgrounds, typography, radius/shapes, borders, rings and outlines.
- There is intentionally **no generic \`tokens.css\` or \`index.css\` layer** in the scaffold. Use normal Tailwind utilities for local layout and spacing (for example \`p-4\`, \`gap-6\`, \`max-w-7xl\`).

Before adding global CSS or a custom visual token, ask: **can Skeleton express this through the theme, a preset, or an existing utility?** If yes, use Skeleton. Only introduce a project-specific abstraction after a concrete, repeated product need exists and Skeleton/Tailwind do not already cover it.

MUST:
- inspect the SvelteForge catalog before writing UI
- reuse existing SvelteForge components before creating new ones
- use Skeleton/Skeleton Svelte for UI primitives and interaction patterns
- change \`svelteforge-theme.css\` first for global visual decisions covered by Skeleton
- use standard Tailwind utilities for local structure, whitespace and responsive layout
- keep pages composition-oriented and thin

MUST NOT:
- install another UI kit
- create a duplicate Button/Input/Card/Dialog/Tabs/Menu/etc. when Skeleton or SvelteForge already provides it
- create project-local one-off design primitives without justification
- create a parallel global palette/token system for colors, surfaces, radius, focus, hover or shadows by default
- add global visual overrides in \`layout.css\` when the Skeleton theme or presets already own the behavior
- redesign the global visual language inside a feature PR

Run \`svforge check\` (via npx/bunx) before finishing a feature — it flags ERROR
violations (second UI kit, duplicated primitives) and WARN (arbitrary values).

### Optional strict pre-commit hook

No Git hook is installed by default. To opt in while scaffolding or re-adding
SvelteForge, select Lefthook (CLI: \`sv add svforge=hooks:lefthook\`). It
installs a \`pre-commit\` hook after dependency installation in a Git
repository (the install is a no-op until you run \`git init\`; re-run your
package manager's install command then) that runs \`node svforge-check.mjs
--strict\`: both WARN and ERROR block the commit. Lefthook only invokes it
when relevant staged \`.svelte\`, \`.html\`, \`.css\`, or \`.json\` files
changed; when invoked, the checker examines the whole project because it has
no partial-file mode. Remove it with \`${pm} remove lefthook\`, delete
\`.lefthook.yml\`, then remove the Lefthook \`prepare\` script entry from
\`package.json\`.

Components wrap Skeleton classes + Tailwind only — never raw CSS
- \`cn()\` + \`class\` prop on every component (merge/override)
- \`HTMLAttributes<T>\` from \`svelte/elements\` for native attribute extension
- \`$bindable()\` declared in the Props interface
- Phosphor icons: \`import X from 'phosphor-svelte/lib/IconName'\`

## Theme

- The complete Skeleton v5 theme lives in \`src/lib/styles/svelteforge-theme.css\` under \`[data-theme='svelteForge']\`.
- Global CSS wiring lives in \`src/routes/layout.css\`; keep it minimal and non-visual.
- Dark mode uses the \`data-mode\` attribute / ThemeToggle component.
- For a project-wide visual change that Skeleton supports, change the theme rather than adding a global override.
- Add a project-specific token/effects layer only later, when a real repeated use case proves it is needed.

## Project commands

\`\`\`bash
${pm} run dev      # dev server
${pm} run build    # production build
${pm} run check    # svelte-check
${pm} run test     # vitest (dashboard: baseline auth/admin tests)
\`\`\`

## Theme, fonts, locales — one source of truth per concern (#322)

The scaffold ships opinionated defaults so the app renders immediately. They are
**defaults, not constraints** — each has exactly one identified source of truth:

- **Theme** (palettes, surfaces, brand, typography roles): \`src/lib/styles/svelteforge-theme.css\` — edit it to replace the palette; the architecture does not change.
- **Fonts**: \`@fontsource-variable/*\` imports in \`src/routes/layout.css\` (Inter body, Space Grotesk headings, Fira Code for \`code\`/\`pre\`). Swap or remove a font there and adjust its role mapping in the theme.
- **Locales / UI copy**: \`messages/*.json\` + \`project.inlang/settings.json\` (see i18n below).

## i18n (Paraglide — #239, #322)

This project ships **Paraglide** (compiler-first i18n). The scaffold starts with
**fr** (baseLocale) and **en** — SVForge's initial locales, NOT a system limit.
Locales live in \`project.inlang/settings.json\`; copy lives in \`messages/<locale>.json\`.

MUST:
- use Paraglide for static user-facing UI copy: \`import * as m from '$lib/paraglide/messages.js'\`
- edit the JSON catalogs in \`messages/\` — NEVER edit generated \`src/lib/paraglide/\` (regenerated at build/dev time)
- add/update EVERY catalog in \`messages/\` — every locale configured in \`project.inlang/settings.json\` — for each UI copy change; key parity across all configured locales is required
- reuse existing message keys when semantics are identical (\`common_save\`, \`common_cancel…\`)
- use domain-oriented message names (\`users_create\`, not \`blue_button_text\`)

MUST NOT:
- hardcode static user-facing copy in Svelte components without a justified exception
- create another i18n/message abstraction
- update only some locales — a feature is not done until every configured locale has the key

Extending locales (a default change, not an architecture change):
- **Adding a locale**: create \`messages/<locale>.json\` with the full key set, then add the locale to \`locales\` in \`project.inlang/settings.json\`.
- **Removing a locale**: delete its catalog and its \`locales\` entry.
- **Changing the base locale**: edit \`baseLocale\` in \`project.inlang/settings.json\`.

Static UI copy belongs in the catalogs. Long-form editorial, business and CMS
content (blog/MDsveX, database) does NOT belong in \`messages/\`.

## LLM resources (vendored, version-matched — offline)

The fresh Skeleton/Svelte references are vendored IN this project — search them
locally instead of fetching remote docs or trusting training memory:

- \`docs/llms-skeleton.txt\`
- \`docs/llms-svelte.txt\`

They are generated from the upstream sources at scaffold time and guarded against
staleness — trust them over training memory.
`;

const DASHBOARD = (pm: string) => `

## Dashboard patterns (this project is a SvelteForge dashboard)

- **Auth**: Better Auth. Session in \`locals.user\` / \`locals.session\` (\`src/hooks.server.ts\`). Login via \`src/routes/login\`.
- **Sign-up is CLOSED by default** (#318): \`SIGNUP_MODE\` in \`.env\` picks the server-enforced mode — \`closed\` (default), \`invite-only\` (pre-approve emails from /admin/users) or \`self-service\`. Unknown values fail closed. Never route sign-up through client-side checks.
- **First admin**: \`${pm} run admin:create -- --name … --email … --password …\` — atomic bootstrap (refuses when an admin exists). \`/setup\` is a dev-only convenience sharing the same code path.
- **Admin role**: explicit persisted \`user.role\` column — granted ONLY by the bootstrap, checked server-side by \`isAdmin()\` (\`src/lib/server/admin.ts\`). Never derive permissions from row ordering (createdAt) and never trust UI protection for authorization.
- **Admin guard**: \`requireAdmin()\` in \`src/routes/(app)/admin/*/+page.server.ts\` — every action calls it BEFORE touching formData or the db.
- **SvelteKit action responses**: \`{ type, data }\` — read the message at \`result.data?.message\`, NEVER \`result.message\` (always undefined).
- **Server errors**: never leak \`e.message\` to the UI — return a generic message.
- **DB**: Drizzle + PostgreSQL. Schema in \`src/lib/server/db/schema.ts\`, config \`drizzle.config.ts\` at the root (dialect postgresql). Env in \`.env\` (copy \`.env.example\` — local / Docker / managed connection strings).
- **Auth schema**: \`src/lib/server/db/auth.schema.ts\` is the runtime-gated source of truth. \`${pm} run auth:schema\` regenerates a REVIEW copy (\`auth-schema.review.ts\`) via the version-lagging CLI — diff it and port deliberate changes manually; never commit it blindly.
- **Validation**: zod schemas in \`src/lib/server/schemas.ts\`.
- **Setup**: \`bash scripts/setup.sh\` creates \`.env\`, generates \`BETTER_AUTH_SECRET\`, pushes the schema. Then create the admin: \`${pm} run admin:create -- --name … --email … --password …\`.
### Golden references (#267) — imitate these screens when building new UI

The admin screens are canonical examples agents should copy:

- **\`/admin/users\`** — CRUD data table: the SvelteForge \`Table\` primitive (columns + \`children\` slot for avatar/badge/actions), search filter, create/edit modal (\`Card\` + \`Input\`), delete confirmation, \`Feedback\` for success/error, empty state. Never hand-roll a raw \`<table>\` (see catalogue \`avoid\`).
- **\`/admin\`** — stats cards (\`Card variant="elevated"\`) + recent list with \`Badge\` status.
- **\`/admin/settings\`** — form with client-side validation + \`Feedback\`.
- **\`AdminLayout\`** — sidebar/mobile drawer with \`aria-expanded\`, \`aria-current\`, labelled navigation.
- **All UI copy is i18n via Paraglide**: import \`* as m from '$lib/paraglide/messages.js'\` and call \`m.key()\` — never hard-code user-visible text. Keys live in EVERY catalog under \`messages/\` (keep parity across all locales configured in \`project.inlang/settings.json\`).
`;

export function scaffoldedAgents(template: 'base' | 'dashboard', packageManager = 'npm'): string {
	// #325: the commands shown to agents must match the PM selected in `sv` —
	// an npm scaffold must never read "bun run …".
	const pm = packageManager.split('@')[0] || 'npm';
	const shared = SHARED(SKELETON_PRIMITIVES.join(', '), SKELETON_INVENTORY, pm);
	return shared + (template === 'dashboard' ? DASHBOARD(pm) : '');
}
