import prettier from 'eslint-config-prettier';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { includeIgnoreFile } from '@eslint/compat';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import tailwindcss from 'eslint-plugin-tailwindcss';
import ts from 'typescript-eslint';
import svforge from './eslint-plugin-svforge.mjs';

const svelteConfigPath = new URL('./svelte.config.js', import.meta.url);
const svelteConfig = existsSync(svelteConfigPath) ? (await import(svelteConfigPath.href)).default : undefined;
const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');
const uiIntegrationFiles = [];
const svforgeManifestPath = path.resolve(import.meta.dirname, '.svforge.json');
if (existsSync(svforgeManifestPath)) {
	try {
		const manifest = JSON.parse(readFileSync(svforgeManifestPath, 'utf8'));
		for (const library of manifest.ui?.libraries ?? []) {
			for (const componentRoot of library.componentRoots ?? []) {
				if (typeof componentRoot !== 'string' || !componentRoot || path.isAbsolute(componentRoot) || /^[a-z]:[\\/]/i.test(componentRoot) || /^[/\\]{2}/.test(componentRoot) || componentRoot.split(/[\\/]/).includes('..')) continue;
				const absoluteRoot = path.resolve(import.meta.dirname, componentRoot);
				const relativeRoot = path.relative(import.meta.dirname, absoluteRoot);
				if (relativeRoot.startsWith(`..${path.sep}`) || path.isAbsolute(relativeRoot)) continue;
				const globRoot = relativeRoot.split(path.sep).join('/');
				uiIntegrationFiles.push(`${globRoot}/**/*.{svelte,svelte.js,svelte.ts}`);
			}
		}
	} catch {
		// svforge-check.mjs reports malformed manifest details without disabling normal lint rules.
	}
}

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// SVForge-owned files are machine-managed (the checker embeds a generated
	// Skeleton inventory; the plugins are upgrade-baseline tracked; the auth
	// schema is regenerated by `auth:schema`) — linting them only produces
	// noise (#325).
	{
		ignores: [
			'svforge-check.mjs',
			'svforge-design-system-vite-plugin.mjs',
			'eslint-plugin-svforge.mjs',
			'src/lib/server/db/auth.schema.ts',
			'auth-schema.review.ts'
		]
	},
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off',
			// _-prefixed props/vars are intentionally unused (e.g. Button's
			// reserved anchor props it must NOT forward) — the convention is
			// part of the scaffold contract (#325).
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
			],
			// SvelteForge primitives and layouts accept arbitrary user hrefs —
			// wrapping them in resolve() is impossible in a generic component
			// and unnecessary for root-relative base paths.
			'svelte/no-navigation-without-resolve': 'off'
		}
	},
	{
		// Test files mock SvelteKit/server boundaries — `any` is the honest
		// type for those seams and `Function` its pragmatic fallback. Ship
		// code stays strict; tests are exempt (#325).
		files: ['**/*.test.ts', '**/*.test.js', '**/*.spec.ts'],
		rules: {
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-unsafe-function-type': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		plugins: { svforge, tailwindcss },
		settings: {
			tailwindcss: {
				// Load the scaffold's real Tailwind v4 entrypoint, including Skeleton,
				// the SvelteForge theme and configured plugins.
				cssConfigPath: 'src/routes/layout.css'
			}
		},
		rules: {
			// Deterministic design-system violations are editor diagnostics too.
			'svforge/no-design-violations': 'error',
			// Validate static class candidates against the configured compiler.
			'tailwindcss/no-custom-classname': 'error'
		}
	},
	...(uiIntegrationFiles.length
		? [{
			files: uiIntegrationFiles,
			rules: {
				// A registered copy-in integration owns its own component API/classes.
				// Scope exemptions to its declared roots; keep all other project checks strict.
				'svforge/no-design-violations': 'off',
				'tailwindcss/no-custom-classname': 'off'
			}
		}]
		: [])
);
